### ISSUE TITLE
helmet.defaults()

### ISSUE THREAD

**Issue by chrisveness** [venables/koa-helmet#15]
The koa-helmet 0.1.0 readme suggested using `app.use(helmet.defaults());`, but this now breaks.

What should the replacement be?

Error:
~~~~
  TypeError: helmet.defaults is not a function
      at Object.<anonymous> (/[...]/apps/www/app-www.js:98:16)
      at Module._compile (module.js:430:26)
      at Object.Module._extensions..js (module.js:448:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Object.subApp (/[...]/app.js:84:37)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (/[...]/node_modules/co/index.js:65:19)
~~~~

**Comment by venables** [comment]
simply use `helmet()`

As we describe in the docs, starting at 0.2.0, koa-helmet is now just a thin wrapper over `helmet`, so following their usage should mimic the usage in koa: https://github.com/helmetjs/helmet

**Comment by chrisveness** [comment]
Thanks
